import Anthropic from '@anthropic-ai/sdk'
import { createClient } from '@/lib/supabase/server'
import { buildSystemPrompt } from '@/lib/prompts'
import { TEMPLATE_BY_ID, ALL_TEMPLATES } from '@/lib/template-ip'
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, ImageRun, Header, PageBreak } from 'docx'
import { NextRequest, NextResponse } from 'next/server'

export const runtime = 'nodejs'
export const maxDuration = 120

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const { data: profile } = await supabase
    .from('profiles')
    .select('*, businesses(*)')
    .eq('id', user.id)
    .single()

  const business = profile?.businesses as any

  const { formData, docType, templateId } = await req.json()

  // Look up template-specific prompt instructions
  const matchedTemplate = templateId
    ? TEMPLATE_BY_ID[templateId]
    : ALL_TEMPLATES.find(t => t.title === docType)

  // Build the prompt from form data
  let detailsPrompt = `Generate a COMPLETE ${docType || 'Employment Contract'} with the following details:\n\n`
  if (formData) {
    for (const [key, value] of Object.entries(formData)) {
      if (value && (value as string).trim()) {
        detailsPrompt += `${key}: ${value}\n`
      }
    }
  }

  if (matchedTemplate?.promptInstructions) {
    // Use template-specific instructions from Humanistiqs IP
    detailsPrompt += `\n${matchedTemplate.promptInstructions}\n\nDo NOT truncate, abbreviate, or summarise. Write every section in full. Use the business profile details for the employer information.`
  } else {
    // Fallback for employment contracts or unknown doc types
    detailsPrompt += `\nGenerate the FULL, COMPLETE document using the Humanistiqs contract template structure. Include EVERY clause — definitions, commencement, position, probation, duties, policies, hours, remuneration, all leave types, confidentiality, IP, non-disparagement, conflicts, relief from duties, termination, restraint, redundancy, assignment, governing law, variation, severability, entire agreement, Fair Work statement, execution blocks, and the Schedule with all Items filled in.\n\nDo NOT truncate, abbreviate, or summarise. Write every clause in full. The document should be 2500-4000 words. Use the business profile details for the employer information.`
  }

  const systemPrompt = buildSystemPrompt('people', {
    name: business?.name || 'Unknown',
    industry: business?.industry || 'General',
    state: business?.state || 'QLD',
    award: business?.award || 'Not specified',
    headcount: business?.headcount || 'Not specified',
    empTypes: business?.employment_types || 'Mixed',
    advisorName: business?.advisor_name || 'Sarah',
    userName: profile?.full_name || '',
  })

  // Call Claude with high token limit for full document
  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 8192,
    system: systemPrompt,
    messages: [{ role: 'user', content: detailsPrompt }],
  })

  const contractText = response.content
    .filter(b => b.type === 'text')
    .map(b => (b as any).text)
    .join('\n')

  // Fetch company logo
  const logoUrl = business?.logo_url
  let logoImageData: Buffer | null = null
  if (logoUrl) {
    try {
      const logoRes = await fetch(logoUrl)
      if (logoRes.ok) {
        logoImageData = Buffer.from(await logoRes.arrayBuffer())
      }
    } catch {}
  }

  // Build header
  const headerChildren: Paragraph[] = []
  if (logoImageData) {
    try {
      headerChildren.push(
        new Paragraph({
          children: [
            new ImageRun({
              data: logoImageData,
              transformation: { width: 150, height: 50 },
              type: 'png',
            }),
          ],
          spacing: { after: 100 },
        })
      )
    } catch {
      if (business?.name) {
        headerChildren.push(
          new Paragraph({
            children: [new TextRun({ text: business.name, bold: true, size: 28, font: 'Calibri', color: '333333' })],
            spacing: { after: 100 },
          })
        )
      }
    }
  } else if (business?.name) {
    headerChildren.push(
      new Paragraph({
        children: [new TextRun({ text: business.name, bold: true, size: 28, font: 'Calibri', color: '333333' })],
        spacing: { after: 100 },
      })
    )
  }

  // Convert contract text to DOCX paragraphs
  const paragraphs = contractToParagraphs(contractText)

  const title = `${docType || 'Employment Contract'} — ${new Date().toLocaleDateString('en-AU')}`

  const document = new Document({
    creator: 'HQ.ai by Humanistiqs',
    title,
    description: `Generated by HQ.ai — ${docType || 'Employment Contract'}`,
    sections: [{
      properties: {},
      headers: headerChildren.length > 0 ? {
        default: new Header({ children: headerChildren }),
      } : undefined,
      children: [
        ...paragraphs,
        new Paragraph({ spacing: { before: 600 }, children: [] }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({
            text: 'Generated by HQ.ai by Humanistiqs — humanistiqs.com.au',
            size: 16, color: 'AAAAAA', italics: true, font: 'Calibri',
          })],
        }),
      ],
    }],
  })

  const buffer = await Packer.toBuffer(document)
  const filename = `${title.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_')}.docx`

  // Also save to documents library
  try {
    await supabase.from('documents').insert({
      business_id: business?.id,
      user_id: user.id,
      title,
      type: (docType || 'employment-contract').toLowerCase().replace(/\s+/g, '-'),
      content: contractText,
    })
  } catch {}

  return new NextResponse(buffer, {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  })
}

function contractToParagraphs(content: string): Paragraph[] {
  const lines = content.split('\n')
  const paragraphs: Paragraph[] = []

  for (const line of lines) {
    const trimmed = line.trim()

    if (!trimmed) {
      paragraphs.push(new Paragraph({ spacing: { after: 80 }, children: [] }))
      continue
    }

    // Main title (# heading)
    if (trimmed.startsWith('# ') && !trimmed.startsWith('## ')) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: trimmed.slice(2), bold: true, size: 32, font: 'Calibri' })],
        spacing: { before: 300, after: 200 },
        alignment: AlignmentType.CENTER,
      }))
    }
    // Section heading (## heading)
    else if (trimmed.startsWith('## ')) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: trimmed.slice(3).toUpperCase(), bold: true, size: 24, font: 'Calibri' })],
        spacing: { before: 300, after: 100 },
      }))
    }
    // Sub heading (### heading)
    else if (trimmed.startsWith('### ')) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [new TextRun({ text: trimmed.slice(4), bold: true, size: 22, font: 'Calibri' })],
        spacing: { before: 200, after: 80 },
      }))
    }
    // Bullet points
    else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      paragraphs.push(new Paragraph({
        bullet: { level: 0 },
        children: parseInline(trimmed.slice(2)),
        spacing: { after: 40 },
      }))
    }
    // Sub-bullets
    else if (trimmed.startsWith('  - ') || trimmed.startsWith('  * ')) {
      paragraphs.push(new Paragraph({
        bullet: { level: 1 },
        children: parseInline(trimmed.slice(4)),
        spacing: { after: 40 },
      }))
    }
    // Numbered items
    else if (/^\d+\.\s/.test(trimmed)) {
      const text = trimmed.replace(/^\d+\.\s/, '')
      paragraphs.push(new Paragraph({
        children: parseInline(text),
        spacing: { after: 60 },
      }))
    }
    // Lettered items (a), b), etc.)
    else if (/^[a-z]\)\s/.test(trimmed)) {
      paragraphs.push(new Paragraph({
        indent: { left: 720 },
        children: parseInline(trimmed),
        spacing: { after: 40 },
      }))
    }
    // Horizontal rule / page break
    else if (trimmed === '---' || trimmed === '***') {
      paragraphs.push(new Paragraph({
        children: [new TextRun({ break: 1 } as any)],
        spacing: { before: 200, after: 200 },
      }))
    }
    // Regular paragraph
    else {
      paragraphs.push(new Paragraph({
        children: parseInline(trimmed),
        spacing: { after: 100 },
      }))
    }
  }

  return paragraphs
}

function parseInline(text: string): TextRun[] {
  const runs: TextRun[] = []
  const parts = text.split(/(\*\*[^*]+\*\*)/)
  for (const part of parts) {
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true, size: 22, font: 'Calibri' }))
    } else {
      runs.push(new TextRun({ text: part, size: 22, font: 'Calibri' }))
    }
  }
  return runs
}
