import { createClient } from '@/lib/supabase/server'
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx'
import { NextRequest, NextResponse } from 'next/server'

export async function GET(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const docId = req.nextUrl.searchParams.get('id')
  if (!docId) return NextResponse.json({ error: 'Missing document ID' }, { status: 400 })

  const { data: doc, error } = await supabase
    .from('documents')
    .select('*')
    .eq('id', docId)
    .single()

  if (error || !doc) {
    return NextResponse.json({ error: 'Document not found' }, { status: 404 })
  }

  // Convert markdown-like content to DOCX paragraphs
  const paragraphs = contentToParagraphs(doc.content)

  const document = new Document({
    creator: 'HQ.ai by Humanistiqs',
    title: doc.title,
    description: `Generated by HQ.ai - ${doc.type || 'Document'}`,
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          children: [new TextRun({ text: doc.title, bold: true, size: 32, font: 'Calibri' })],
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200 },
        }),
        new Paragraph({
          children: [new TextRun({
            text: `${doc.type || 'Document'} - Generated by HQ.ai on ${new Date(doc.created_at).toLocaleDateString('en-AU')}`,
            size: 18, color: '888888', font: 'Calibri',
          })],
          spacing: { after: 400 },
        }),
        ...paragraphs,
        new Paragraph({ spacing: { before: 600 }, children: [] }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({
            text: 'Generated by HQ.ai by Humanistiqs - humanistiqs.com.au',
            size: 16, color: 'AAAAAA', italics: true, font: 'Calibri',
          })],
        }),
      ],
    }],
  })

  const buffer = await Packer.toBuffer(document)
  const filename = `${doc.title.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_')}.docx`

  return new NextResponse(buffer, {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  })
}

function contentToParagraphs(content: string): Paragraph[] {
  const lines = content.split('\n')
  const paragraphs: Paragraph[] = []

  for (const line of lines) {
    const trimmed = line.trim()

    if (!trimmed) {
      paragraphs.push(new Paragraph({ spacing: { after: 100 }, children: [] }))
      continue
    }

    // Headings
    if (trimmed.startsWith('### ')) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [new TextRun({ text: trimmed.slice(4), bold: true, size: 24, font: 'Calibri' })],
        spacing: { before: 200, after: 100 },
      }))
    } else if (trimmed.startsWith('## ')) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: trimmed.slice(3), bold: true, size: 28, font: 'Calibri' })],
        spacing: { before: 300, after: 100 },
      }))
    } else if (trimmed.startsWith('# ')) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: trimmed.slice(2), bold: true, size: 32, font: 'Calibri' })],
        spacing: { before: 300, after: 200 },
      }))
    }
    // Bullet points
    else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      paragraphs.push(new Paragraph({
        bullet: { level: 0 },
        children: parseInlineFormatting(trimmed.slice(2)),
        spacing: { after: 60 },
      }))
    }
    // Numbered items - keep the literal "1. " prefix as text rather than
    // using docx numbering refs (which require a numbering config block in
    // the Document and corrupt the file when the ref is undefined).
    else if (/^\d+\.\s/.test(trimmed)) {
      paragraphs.push(new Paragraph({
        children: parseInlineFormatting(trimmed),
        spacing: { after: 60 },
      }))
    }
    // Regular paragraph
    else {
      paragraphs.push(new Paragraph({
        children: parseInlineFormatting(trimmed),
        spacing: { after: 120 },
      }))
    }
  }

  return paragraphs
}

function parseInlineFormatting(text: string): TextRun[] {
  const runs: TextRun[] = []
  // Simple bold (**text**) parsing
  const parts = text.split(/(\*\*[^*]+\*\*)/)
  for (const part of parts) {
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true, size: 22, font: 'Calibri' }))
    } else {
      runs.push(new TextRun({ text: part, size: 22, font: 'Calibri' }))
    }
  }
  return runs
}
