import { createClient } from '@/lib/supabase/server'
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, ImageRun, Header } from 'docx'
import { NextRequest, NextResponse } from 'next/server'

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const { content, title, docType } = await req.json()
  if (!content) return NextResponse.json({ error: 'No content provided' }, { status: 400 })

  // Get business details and logo
  const { data: profile } = await supabase
    .from('profiles')
    .select('*, businesses(*)')
    .eq('id', user.id)
    .single()

  const business = profile?.businesses as any
  const logoUrl = business?.logo_url

  // Try to fetch logo image for header
  let logoImageData: Buffer | null = null
  if (logoUrl) {
    try {
      const logoRes = await fetch(logoUrl)
      if (logoRes.ok) {
        const arrayBuf = await logoRes.arrayBuffer()
        logoImageData = Buffer.from(arrayBuf)
      }
    } catch {
      // Logo fetch failed — continue without it
    }
  }

  // Build header with logo
  const headerChildren: Paragraph[] = []
  if (logoImageData) {
    try {
      headerChildren.push(
        new Paragraph({
          children: [
            new ImageRun({
              data: logoImageData,
              transformation: { width: 150, height: 50 },
              type: 'png',
            }),
          ],
          spacing: { after: 200 },
        })
      )
    } catch {
      // If image fails to embed, add business name text instead
      headerChildren.push(
        new Paragraph({
          children: [new TextRun({
            text: business?.name || 'Company',
            bold: true, size: 28, font: 'Calibri', color: '333333',
          })],
          spacing: { after: 200 },
        })
      )
    }
  } else if (business?.name) {
    headerChildren.push(
      new Paragraph({
        children: [new TextRun({
          text: business.name,
          bold: true, size: 28, font: 'Calibri', color: '333333',
        })],
        spacing: { after: 200 },
      })
    )
  }

  // Convert markdown content to DOCX paragraphs
  const paragraphs = contentToParagraphs(content)

  const docTitle = title || `${docType || 'Document'} — ${new Date().toLocaleDateString('en-AU')}`

  const document = new Document({
    creator: 'HQ.ai by Humanistiqs',
    title: docTitle,
    description: `Generated by HQ.ai — ${docType || 'Document'}`,
    sections: [{
      properties: {},
      headers: headerChildren.length > 0 ? {
        default: new Header({ children: headerChildren }),
      } : undefined,
      children: [
        new Paragraph({
          children: [new TextRun({ text: docTitle, bold: true, size: 32, font: 'Calibri' })],
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200 },
        }),
        new Paragraph({
          children: [new TextRun({
            text: `${docType || 'Document'} — Generated by HQ.ai on ${new Date().toLocaleDateString('en-AU')}`,
            size: 18, color: '888888', font: 'Calibri',
          })],
          spacing: { after: 400 },
        }),
        ...paragraphs,
        new Paragraph({ spacing: { before: 600 }, children: [] }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({
            text: 'Generated by HQ.ai by Humanistiqs — humanistiqs.com.au',
            size: 16, color: 'AAAAAA', italics: true, font: 'Calibri',
          })],
        }),
      ],
    }],
  })

  const buffer = await Packer.toBuffer(document)
  const filename = `${docTitle.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_')}.docx`

  return new NextResponse(buffer, {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  })
}

function contentToParagraphs(content: string): Paragraph[] {
  const lines = content.split('\n')
  const paragraphs: Paragraph[] = []

  for (const line of lines) {
    const trimmed = line.trim()

    if (!trimmed) {
      paragraphs.push(new Paragraph({ spacing: { after: 100 }, children: [] }))
      continue
    }

    if (trimmed.startsWith('### ')) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [new TextRun({ text: trimmed.slice(4), bold: true, size: 24, font: 'Calibri' })],
        spacing: { before: 200, after: 100 },
      }))
    } else if (trimmed.startsWith('## ')) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: trimmed.slice(3), bold: true, size: 28, font: 'Calibri' })],
        spacing: { before: 300, after: 100 },
      }))
    } else if (trimmed.startsWith('# ')) {
      paragraphs.push(new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: trimmed.slice(2), bold: true, size: 32, font: 'Calibri' })],
        spacing: { before: 300, after: 200 },
      }))
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      paragraphs.push(new Paragraph({
        bullet: { level: 0 },
        children: parseInlineFormatting(trimmed.slice(2)),
        spacing: { after: 60 },
      }))
    } else if (/^\d+\.\s/.test(trimmed)) {
      const text = trimmed.replace(/^\d+\.\s/, '')
      paragraphs.push(new Paragraph({
        children: parseInlineFormatting(text),
        spacing: { after: 60 },
      }))
    } else {
      paragraphs.push(new Paragraph({
        children: parseInlineFormatting(trimmed),
        spacing: { after: 120 },
      }))
    }
  }

  return paragraphs
}

function parseInlineFormatting(text: string): TextRun[] {
  const runs: TextRun[] = []
  const parts = text.split(/(\*\*[^*]+\*\*)/)
  for (const part of parts) {
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true, size: 22, font: 'Calibri' }))
    } else {
      runs.push(new TextRun({ text: part, size: 22, font: 'Calibri' }))
    }
  }
  return runs
}
