// Create / re-price every one-off document SKU (and the 2 packs) in Stripe.
//
// The revised one-off ladder (July 2026) changed all 10 document prices and
// added Employment Pack ($349) + Award Pack ($599). Stripe Prices are
// immutable, so a re-price means minting a NEW price at the new amount. This
// script does all 12 in one run, driven entirely by PRICING.oneOffs in
// lib/pricing-config.ts (never hardcoded here):
//   - one Stripe Product per SKU (name = sku.name), reused on re-run
//   - one one-time AUD Price per SKU at sku.price
//
// Idempotent + re-price aware, keyed by lookup_key = sku.id:
//   - no existing price          -> create it
//   - existing price, same amount -> reuse (no change)
//   - existing price, new amount  -> create new price, transfer the lookup_key
//     onto it, and ARCHIVE the old price (active: false)
//
// Reads STRIPE_SECRET_KEY from .env.local (or the environment); the key is
// never printed, only its live/test mode. Run from the hqai/ directory:
//   npx tsx scripts/stripe-oneoff-ladder-setup.ts
//
// Output: scripts/stripe-oneoff-price-ids.env (paste the whole block into
// Vercel env: Production + Preview + Development), and any missing keys are
// appended to .env.local so local dev resolves immediately.

import { readFileSync, writeFileSync, appendFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import Stripe from 'stripe'
import { PRICING } from '../lib/pricing-config'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ENV_LOCAL = join(__dirname, '..', '.env.local')

function loadEnvKey(name: string): string | null {
  if (process.env[name]?.trim()) return process.env[name]!.trim()
  if (!existsSync(ENV_LOCAL)) return null
  for (const line of readFileSync(ENV_LOCAL, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/)
    if (m && m[1] === name) return m[2].trim().replace(/^["']|["']$/g, '')
  }
  return null
}

function envHasKey(name: string): boolean {
  if (!existsSync(ENV_LOCAL)) return false
  return readFileSync(ENV_LOCAL, 'utf8').split(/\r?\n/).some((l) => l.startsWith(`${name}=`))
}

async function main() {
  const key = loadEnvKey('STRIPE_API_KEY') ?? loadEnvKey('STRIPE_SECRET_KEY')
  if (!key) {
    console.error('No STRIPE_SECRET_KEY in .env.local or environment. Aborting.')
    process.exit(1)
  }
  const mode = key.startsWith('sk_live') ? 'LIVE' : key.startsWith('sk_test') ? 'TEST' : 'UNKNOWN'
  console.log(`Stripe mode: ${mode}`)
  if (mode === 'LIVE') console.log('WARNING: operating on your LIVE Stripe account.\n')

  const stripe = new Stripe(key, { apiVersion: '2024-04-10' })

  const results: { envKey: string; priceId: string }[] = []

  for (const sku of PRICING.oneOffs) {
    const lookup = sku.id // e.g. 'letter-of-offer'
    const amountCents = sku.price * 100

    // Any existing price carrying this lookup_key?
    const existing = (await stripe.prices.list({ lookup_keys: [lookup], limit: 1 })).data[0] ?? null

    // Same price already live -> reuse, nothing to do.
    if (existing && existing.active && existing.unit_amount === amountCents) {
      console.log(`  reuse   ${sku.name} ($${sku.price}) -> ${existing.id}`)
      results.push({ envKey: sku.stripePriceId, priceId: existing.id })
      continue
    }

    // Resolve or create the product (reuse the old price's product when re-pricing).
    let productId = (existing?.product as string | undefined) ?? null
    if (!productId) {
      const found = await stripe.products.search({ query: `name:'${sku.name}'`, limit: 1 })
      productId = found.data[0]?.id ?? null
    }
    if (!productId) {
      const product = await stripe.products.create({ name: sku.name, description: sku.description })
      productId = product.id
      console.log(`  product created: ${sku.name} -> ${productId}`)
    }

    // Mint the new one-time price; move the lookup_key off the old price if present.
    const price = await stripe.prices.create({
      product: productId,
      unit_amount: amountCents,
      currency: 'aud',
      nickname: `${sku.name} ($${sku.price})`,
      lookup_key: lookup,
      ...(existing ? { transfer_lookup_key: true } : {}),
    })
    if (existing) {
      await stripe.prices.update(existing.id, { active: false })
      console.log(`  reprice ${sku.name} $${sku.price} -> ${price.id}  (archived old ${existing.id})`)
    } else {
      console.log(`  create  ${sku.name} $${sku.price} -> ${price.id}`)
    }
    results.push({ envKey: sku.stripePriceId, priceId: price.id })
  }

  // Write the paste-into-Vercel env block.
  const outPath = join(__dirname, 'stripe-oneoff-price-ids.env')
  writeFileSync(
    outPath,
    [
      '# One-off document + pack Stripe price ids (revised July 2026 ladder).',
      '# Generated by scripts/stripe-oneoff-ladder-setup.ts',
      '# Paste into Vercel env (Production + Preview + Development), then redeploy.',
      ...results.map((r) => `${r.envKey}=${r.priceId}`),
      '',
    ].join('\n'),
    'utf8',
  )
  console.log(`\nWrote ${results.length} price ids to ${outPath}`)

  // Append any missing keys to .env.local for immediate local resolution.
  const toAppend = results.filter((r) => !envHasKey(r.envKey)).map((r) => `${r.envKey}=${r.priceId}`)
  if (toAppend.length && existsSync(ENV_LOCAL)) {
    appendFileSync(ENV_LOCAL, `\n# One-off ladder (stripe-oneoff-ladder-setup.ts)\n${toAppend.join('\n')}\n`)
    console.log(`Appended ${toAppend.length} key(s) to .env.local`)
  } else {
    console.log('.env.local already has all keys (or file missing) - nothing appended')
  }

  console.log('\nNext: paste scripts/stripe-oneoff-price-ids.env into Vercel and redeploy.')
  console.log('Note: prices that already existed at old amounts were archived (active:false);')
  console.log('any old prices created without a lookup_key are left untouched - archive them in the Stripe dashboard if you want a tidy catalogue.')
}

main().catch((err) => {
  console.error('FAILED:', err?.message ?? err)
  process.exit(1)
})
