// Create the advisory-hour one-off product + price in Stripe.
//
// The onboarding Support step lets a buyer "book advisory time now" - a
// dedicated Humanistiqs advisor's time at $250/hour, charged once at
// checkout. It is added to the subscription-mode Checkout Session as a
// one-time line item with quantity = number of hours (Stripe bills one-time
// prices on the initial invoice only). Until this price exists and
// STRIPE_PRICE_ID_ADVISORY_HOUR is set, the checkout route 503s with a
// friendly "not switched on yet" message rather than charging.
//
// This creates:
//   - product "HQ.ai Advisory Time"
//   - $250 AUD ONE-OFF price (no recurring) -> STRIPE_PRICE_ID_ADVISORY_HOUR
//     (quantity is set per checkout = the number of hours booked)
//
// Amount comes from lib/pricing-config.ts (ADVISORY_HOURS.hourlyRate) -
// never hardcoded here. Idempotent: the price carries a lookup_key and is
// reused on re-run.
//
// Reads STRIPE_SECRET_KEY from .env.local (or the environment). The key is
// never printed - only its live/test mode. Run with:
//   npx tsx scripts/stripe-advisory-hour-setup.ts
//
// Output: scripts/stripe-advisory-hour-price-ids.env (paste into Vercel),
// and the line is appended to .env.local if absent.

import { readFileSync, writeFileSync, appendFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import Stripe from 'stripe'
import { resolveStripeKey } from './stripe-key'
import { ADVISORY_HOURS } from '../lib/pricing-config'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ENV_LOCAL = join(__dirname, '..', '.env.local')

function envHasKey(name: string): boolean {
  if (!existsSync(ENV_LOCAL)) return false
  return readFileSync(ENV_LOCAL, 'utf8')
    .split(/\r?\n/)
    .some((l) => l.startsWith(`${name}=`))
}

const LOOKUP_ADVISORY_HOUR = 'advisory_hour_oneoff'
const PRODUCT_NAME = 'HQ.ai Advisory Time'

async function main() {
  const _r = resolveStripeKey(ENV_LOCAL)
  const key = _r.key
  if (!key) {
    console.error('No STRIPE_SECRET_KEY in .env.local or environment. Aborting.')
    process.exit(1)
  }
  const mode = _r.mode
  console.log(`Stripe mode: ${mode}  (candidates -> live:${_r.liveCount} test:${_r.testCount} other:${_r.otherCount})`)

  const stripe = new Stripe(key, { apiVersion: '2024-04-10' })

  const hourAud = ADVISORY_HOURS.hourlyRate // $250

  // Idempotency: reuse a price that already carries our lookup key.
  const existing = await stripe.prices.list({
    lookup_keys: [LOOKUP_ADVISORY_HOUR],
    limit: 10,
  })
  let hourPrice = existing.data.find((p) => p.lookup_key === LOOKUP_ADVISORY_HOUR) ?? null

  // Resolve or create the product.
  let productId = (hourPrice?.product as string | undefined) ?? null
  if (!productId) {
    const found = await stripe.products.search({ query: `name:'${PRODUCT_NAME}'`, limit: 1 })
    productId = found.data[0]?.id ?? null
  }
  if (!productId) {
    const product = await stripe.products.create({
      name: PRODUCT_NAME,
      description:
        'One-off advisory time with a dedicated Humanistiqs HR or talent advisor, booked by the hour. Charged once at checkout; quantity is the number of hours booked.',
    })
    productId = product.id
    console.log(`  product created: ${PRODUCT_NAME} -> ${productId}`)
  } else {
    console.log(`  product reused: ${PRODUCT_NAME} -> ${productId}`)
  }

  if (!hourPrice) {
    hourPrice = await stripe.prices.create({
      product: productId,
      unit_amount: hourAud * 100,
      currency: 'aud',
      // NO `recurring` - this is a one-off price. Quantity is set per
      // checkout to the number of hours booked.
      nickname: `HQ.ai advisory time ($${hourAud}/hour, one-off)`,
      lookup_key: LOOKUP_ADVISORY_HOUR,
    })
    console.log(`  price created: $${hourAud}/hour one-off -> ${hourPrice.id}`)
  } else {
    console.log(`  price reused: advisory hour -> ${hourPrice.id}`)
  }

  // Write the paste-into-Vercel env block.
  const outPath = join(__dirname, 'stripe-advisory-hour-price-ids.env')
  writeFileSync(
    outPath,
    [
      '# HQ.ai advisory-hour Stripe price id. Paste into Vercel env (and .env.local).',
      '# Generated by scripts/stripe-advisory-hour-setup.ts',
      `STRIPE_PRICE_ID_ADVISORY_HOUR=${hourPrice.id}`,
      '',
    ].join('\n'),
    'utf8',
  )
  console.log(`\nWrote id to ${outPath}`)

  // Append to .env.local so local dev resolves immediately (skip if present).
  if (!envHasKey('STRIPE_PRICE_ID_ADVISORY_HOUR') && existsSync(ENV_LOCAL)) {
    appendFileSync(ENV_LOCAL, `\n# Advisory hours (stripe-advisory-hour-setup.ts)\nSTRIPE_PRICE_ID_ADVISORY_HOUR=${hourPrice.id}\n`)
    console.log('Appended STRIPE_PRICE_ID_ADVISORY_HOUR to .env.local')
  } else {
    console.log('.env.local already has the key (or file missing) - nothing appended')
  }

  console.log('Next: paste the id into Vercel (Production + Preview + Development) and redeploy.')
}

main().catch((err) => {
  console.error('FAILED:', err?.message ?? err)
  process.exit(1)
})
