#!/usr/bin/env python3
"""
Create the HQ.ai v2 pricing catalogue in Stripe via the Stripe CLI.

Reads the Stripe secret key from the STRIPE_API_KEY env var (never printed).
Creates products + prices and writes the resulting price ids as a ready-to-
paste env block to scripts/stripe-v2-price-ids.env.

Amounts are AUD cents. Mirrors lib/pricing-config.ts + CLAUDE.md pricing.
Run via run-stripe-v2-setup.sh which supplies the key + CLI path.
"""
import json
import os
import subprocess
import sys

STRIPE = os.environ["STRIPE_BIN"]
KEY = os.environ["STRIPE_API_KEY"]


def run(args):
    out = subprocess.run(
        [STRIPE, *args, "--api-key", KEY],
        capture_output=True, text=True,
    )
    if out.returncode != 0:
        sys.stderr.write(f"FAILED: stripe {' '.join(args)}\n{out.stderr}\n")
        sys.exit(1)
    return json.loads(out.stdout)


def create_product(name):
    obj = run(["products", "create", "--name", name])
    print(f"  product: {name} -> {obj['id']}")
    return obj["id"]


def create_price(product_id, amount, interval, nickname):
    args = ["prices", "create", "--product", product_id,
            "--unit-amount", str(amount), "--currency", "aud",
            "-d", f"nickname={nickname}"]
    if interval:  # 'month' or 'year' for recurring; None for one-time
        args += ["-d", f"recurring[interval]={interval}"]
    obj = run(args)
    print(f"    price: {nickname} ({amount}c {interval or 'one-time'}) -> {obj['id']}")
    return obj["id"]


def main():
    ids = {}

    # -- Subscriptions --------------------------------------------------
    solo = create_product("HQ.ai Solo")
    ids["STRIPE_PRICE_ID_SOLO_MONTHLY"] = create_price(solo, 8900, "month", "Solo monthly")
    ids["STRIPE_PRICE_ID_SOLO_ANNUAL"] = create_price(solo, 89000, "year", "Solo annual")

    biz = create_product("HQ.ai Business")
    ids["STRIPE_PRICE_ID_BUSINESS_MONTHLY"] = create_price(biz, 24900, "month", "Business monthly")
    ids["STRIPE_PRICE_ID_BUSINESS_ANNUAL"] = create_price(biz, 249000, "year", "Business annual")
    ids["STRIPE_PRICE_ID_BUSINESS_FOUNDATION"] = create_price(biz, 214800, "year", "Business Foundation 100 (annual, locked)")

    # -- Enterprise (sales-assisted; recurring) -------------------------
    ent_people = create_product("HQ People Enterprise")
    ids["STRIPE_PRICE_ID_ENTERPRISE_PEOPLE_ANNUAL"] = create_price(ent_people, 1794000, "year", "HQ People Enterprise annual")
    ids["STRIPE_PRICE_ID_ENTERPRISE_PEOPLE_MONTHLY"] = create_price(ent_people, 179500, "month", "HQ People Enterprise monthly")

    ent_recruit = create_product("HQ Recruit Enterprise")
    ids["STRIPE_PRICE_ID_ENTERPRISE_RECRUIT_ANNUAL"] = create_price(ent_recruit, 3594000, "year", "HQ Recruit Enterprise annual")
    ids["STRIPE_PRICE_ID_ENTERPRISE_RECRUIT_MONTHLY"] = create_price(ent_recruit, 349500, "month", "HQ Recruit Enterprise monthly")

    ent_full = create_product("Full Enterprise")
    ids["STRIPE_PRICE_ID_ENTERPRISE_FULL_ANNUAL"] = create_price(ent_full, 4794000, "year", "Full Enterprise annual")
    ids["STRIPE_PRICE_ID_ENTERPRISE_FULL_MONTHLY"] = create_price(ent_full, 449500, "month", "Full Enterprise monthly")

    # -- One-off marketplace (one-time) ---------------------------------
    oneoffs = [
        ("STRIPE_PRICE_ID_LETTER_OF_OFFER", "Letter of Offer", 2500),
        ("STRIPE_PRICE_ID_TERMINATION", "Termination Letter", 4500),
        ("STRIPE_PRICE_ID_EMPLOYMENT_CONTRACT", "Employment Contract", 4900),
        ("STRIPE_PRICE_ID_FIRST_FINAL_WARNING", "First and Final Warning", 3500),
        ("STRIPE_PRICE_ID_POSITION_DESCRIPTION", "Position Description", 2900),
        ("STRIPE_PRICE_ID_PERFORMANCE_PLAN", "Performance Plan (PIP)", 3900),
        ("STRIPE_PRICE_ID_CASUAL_CONVERSION", "Casual Conversion", 2900),
        ("STRIPE_PRICE_ID_RESIGNATION_ACCEPTANCE", "Resignation Acceptance", 2500),
        ("STRIPE_PRICE_ID_PROBATION_OUTCOME", "Probation Outcome", 3500),
        ("STRIPE_PRICE_ID_REFERENCE_CHECK", "Reference Check", 2500),
    ]
    for env_var, name, amount in oneoffs:
        prod = create_product(f"HQ.ai - {name}")
        ids[env_var] = create_price(prod, amount, None, name)

    # -- Write the env block --------------------------------------------
    out_path = os.path.join(os.path.dirname(__file__), "stripe-v2-price-ids.env")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# HQ.ai v2 Stripe price ids (TEST mode). Paste into Vercel env.\n")
        f.write("# Generated by scripts/stripe-v2-setup.py\n\n")
        for k, v in ids.items():
            f.write(f"{k}={v}\n")
    print(f"\nWrote {len(ids)} price ids to {out_path}")


if __name__ == "__main__":
    main()
